### ISSUE TITLE
A Game Of Thrones - Error 404

### ISSUE THREAD

**Issue by NCDKorrigan** [jrmitch120/OctgnImageDb#1]
URL changed from http://188.226.190.230/api/packs/
to http://188.226.190.230/api/public/packs/

**Comment by NCDKorrigan** [comment]
Oh and the sets URL changed too.

Got2DbImages.cs#L30 should read:
            dynamic apiSets = Json.Decode(wc.DownloadString(ApiBaseUrl + "/api/public/packs/"));
Got2DbImages.cs#L47 should read:
                dynamic apiCards = Json.Decode(wc.DownloadString(ApiBaseUrl + "/api/public/cards/" + apiSet.code));

**Comment by NCDKorrigan** [comment]
Set mapping is broken too ("Taking the Black" is already on OCTGN but doesnt get mapped).

**Comment by jrmitch120** [comment]
Hey NCDKorrigan.  

Thanks for the heads up on the API change.  I'll fix it and create a new release.

Set mapping should be based on which sets are installed in OCTGN.  From what I can tell, only Core is available.  Can you point me at something that shows Taking the Black is available?

**Comment by NCDKorrigan** [comment]
I don't know who maintains the plugin so I can't point you at an official announcement, but I played on Sunday and Taking the Black is available and named "02-Westeros".

**Comment by jrmitch120** [comment]
Thanks.  Usually maintainers have kept sets separate.  It looks like they plan to roll all of the Westeros cycle together in a single set.  

This should now be handled in release [1.3.1](https://github.com/jrmitch120/OctgnImageDb/releases/tag/1.3.1).
