### ISSUE TITLE
Missing Card Image

### ISSUE THREAD

**Issue by pandamannoah** [jrmitch120/OctgnImageDb#2]
The downloader misses the faction cards for aGoT 2.0.

**Comment by jrmitch120** [comment]
I don't believe [thronesdb](http://thronesdb.com) has them available.  Are you able to source them there?

**Comment by pandamannoah** [comment]
I didn't find the card in the "cards" list but they definitely have the
images because you can see them when you load your deck. I was able to work
around this issue. I ended up installing the censored image pack and then
re-running OctgnImageDb to re-load the uncensored images.

First I had tried to just find the file for the faction card in the Octgn
Image folder and replace the image from a manually downloaded image of the
faction card but OctgnImageDb didn't even make the file for the faction
card, so I had to find another way to get it into Octgn's images folder. So
the problem is solved for me but would be nice to get the image from the
downloader or at least a placeholder to make fixing the problem easier/more
straightforward. Just my $0.02.

Thanks for replying!

**Comment by jrmitch120** [comment]
I just took a look at the censored image pack.  The censored pack contains uncensored versions of the faction cards which explains why your loading of the pack works in the manner you describe.  [thronesdb](http://thronesdb.com) (which is used to source the OctgnImageDb images for AGOT 2.0) doesn't have the faction cards available.  There is no is no way to obtain these images without doing as you've done.

If [thronesdb](http://thronesdb.com) makes these available, we can get them through the import process.  However, until then, you'll have to do as you've done.
